Sound and music
KD-lab-Open-Source/Samogonki pull request #19
Opened 2023-05-03 08:53 UTC by ivan-ushakov

2023-05-17 09:24 UTC, caiiiycuk requested changes

2023-05-17 09:24 UTC, caiiiycuk commented on MechoSoma/CMakeLists.txt
> +include_directories(../3rdparty/miniaudio)
предлагаю добавить ffmpeg и miniaudio как submodule (по аналогии с sokol-tools-bin)

2023-05-17 09:24 UTC, caiiiycuk commented on .github/workflows/windows.yaml
> +        msys2 -c 'mingw32-make -j4'
насчет 4 не уверен

2023-05-17 09:24 UTC, caiiiycuk commented on MechoSoma/Sound/audio_file.cpp
> +      throw std::runtime_error("avformat_find_stream_info");
почему не стал использовать XAssert?

2023-05-17 09:24 UTC, caiiiycuk commented on MechoSoma/XTool/xsound.cpp
> +    printf("ERROR: %s\n", e.what());
лучше избавиться от try/catch webassembly медленно работает с ними, хотя и не критично, но кажется избавиться от try/catch тут не сложно

2023-05-17 09:27 UTC, caiiiycuk requested changes
Зачем кстате iconv и libz нужен? Надо в акшон добавить копирование dll

2023-05-18 20:21 UTC, ivan-ushakov commented
> Зачем кстате iconv и libz нужен? Надо в акшон добавить копирование dll

Эти две требуются для FFmpeg. По DLL - я собираю FFmpeg как статичную библиотеку

2023-05-18 20:22 UTC, ivan-ushakov commented on MechoSoma/Sound/audio_file.cpp
> +      throw std::runtime_error("avformat_find_stream_info");
Согласен, давай поменяем на `XAssert`, все равно любая ошибка там это некорректное поведение программы, и нужно завершать процесс

2023-05-18 20:23 UTC, ivan-ushakov commented on .github/workflows/windows.yaml
> +        msys2 -c 'mingw32-make -j4'
Я сделал по [аналогии](https://github.com/KranX/Vangers/blob/master/.github/workflows/vangers_windows_64_build.yml#L54)

2023-05-18 20:23 UTC, ivan-ushakov commented on MechoSoma/CMakeLists.txt
> +include_directories(../3rdparty/miniaudio)
Согласен, сделаю

2023-05-19 14:50 UTC, ivan-ushakov commented on MechoSoma/CMakeLists.txt
> +include_directories(../3rdparty/miniaudio)
Тогда и сам Sokol нужно переводить на submodule, иначе будет солянка: тут делаем так, а тут иначе

2023-05-19 15:48 UTC, caiiiycuk commented on MechoSoma/CMakeLists.txt
> +include_directories(../3rdparty/miniaudio)
c Sokol проблема в том что он у нас патченый, это надо форкать тогда... кстате Ffmpeg можно ещё через ExternalProject_Add собирать тоже удобная штука. 
кстате а почему мы FFMPEG не ищем через cmake? 
```
FIND_PACKAGE(FFMPEG REQUIRED)
```

2023-05-19 16:01 UTC, caiiiycuk commented on MechoSoma/CMakeLists.txt
> +include_directories(../3rdparty/miniaudio)
А наверное потому что статическая либа? А есть смысл от того что она статическая?

2023-05-20 17:18 UTC, ivan-ushakov commented on MechoSoma/CMakeLists.txt
> +include_directories(../3rdparty/miniaudio)
А что дает динамическая? Статичная упрощает дистрибуцию, меньше файлов

2023-05-20 17:46 UTC, ivan-ushakov commented on MechoSoma/CMakeLists.txt
> +include_directories(../3rdparty/miniaudio)
Я перевел Miniaudio на subnodule, потому что там не требуется сборка и установка. По FFmpeg я оставил бы процесс как есть

2023-05-20 20:16 UTC, caiiiycuk commented on MechoSoma/CMakeLists.txt
> +include_directories(../3rdparty/miniaudio)
Динамическую либу в теории можно не собирать, а просто установить как зависимость. Можно так оставить, но не мог бы ты добавить инструкцию сборки в README.md

2023-05-20 20:19 UTC, caiiiycuk commented
> > Зачем кстате iconv и libz нужен? Надо в акшон добавить копирование dll
> 
> Эти две требуются для FFmpeg. По DLL - я собираю FFmpeg как статичную библиотеку

Да но соборка из action не работает из-за недостающих библиотек. В Вангерах мы их копируем, как то так:
```
        msys2 -c 'cp /mingw64/bin/SDL2.dll vangers/bin/'
        msys2 -c 'cp /mingw64/bin/SDL2_net.dll vangers/bin/'
        msys2 -c 'cp /mingw64/bin/avcodec-58.dll vangers/bin/'
        msys2 -c 'cp /mingw64/bin/avformat-58.dll vangers/bin/'
        msys2 -c 'cp /mingw64/bin/avutil-56.dll vangers/bin/'
        msys2 -c 'cp /mingw64/bin/libogg-0.dll vangers/bin/'
        msys2 -c 'cp /mingw64/bin/libvorbis-0.dll vangers/bin/'
        msys2 -c 'cp /mingw64/bin/libvorbisfile-3.dll vangers/bin/'
        msys2 -c 'cp /mingw64/bin/zlib1.dll vangers/bin/'
        msys2 -c 'cp /mingw64/bin/libgcc_s_dw2-1.dll vangers/bin/'
        msys2 -c 'cp /mingw64/bin/libgcc_s_seh-1.dll vangers/bin/'
        msys2 -c 'cp /mingw64/bin/libstdc++-6.dll vangers/bin/'
        msys2 -c 'cp /mingw64/bin/libwinpthread-1.dll vangers/bin/'
```

2023-05-21 08:34 UTC, ivan-ushakov commented
> Да но соборка из action не работает из-за недостающих библиотек. В Вангерах мы их копируем, как то так:

Добавил копирование DLL

2023-05-22 09:14 UTC, merged