feat: add widescreen options
KD-lab-Open-Source/Samogonki pull request #96
Opened 2024-05-14 15:46 UTC by Solant

Added widescreen options to menu

I had issues finding a way to recompile `ISCREEN.SCR` file, but it should be working fine

This change is backwards compatible, as new options are added after index `6`, so old `ISCREEN.scb` can't use them due to `max_state 5`

2024-05-14 15:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/KD-lab-Open-Source/Samogonki?pullRequest=96) <br/>All committers have signed the CLA.

2024-06-09 08:05 UTC, ivan-ushakov requested changes

2024-06-09 08:05 UTC, ivan-ushakov commented on MechoSoma/iScreen/SCRIPTS/ACI_STR.INC
> +#define ACS_1280_720_STR	"1280x720"
Тут не нужно менять, мы не собираем экраны из этих файлов

2024-06-09 08:05 UTC, ivan-ushakov commented on MechoSoma/iScreen/SCRIPTS/ISCREEN.SCR
> +		state_str $ACS_1280_720_STR
Тут аналогично не меняем

2024-06-09 08:05 UTC, ivan-ushakov commented on MechoSoma/iScreen/I-World.cpp
> +#include <aspect_ratio.h>
`#include "aspect_ratio.h"`

2024-06-09 08:05 UTC, ivan-ushakov commented on MechoSoma/RUNTIME/intro_movie.cpp
>  			xx = float(i << 8) * scale_x;
`AR_CURRENT->offset * 2` лучше добавить тут, чтобы строка ниже осталась без изменений

2024-06-09 08:05 UTC, ivan-ushakov commented on MechoSoma/RUNTIME/arcane_menu.cpp
> +	// widescreen patches
Это лучше вынести в метод внутри AspectRatio, чтобы не распылять логику

2024-06-18 18:50 UTC, ivan-ushakov commented on MechoSoma/RUNTIME/arcane_menu.cpp
> +	// mch_arcScrD->objList->search(AE_BONUS_PART)->InitCoords("bonus_part");
А это не будет получается перерисовывать?

2024-06-18 18:51 UTC, ivan-ushakov commented on MechoSoma/RUNTIME/arcane_menu.cpp
> +void mchReInitArcaneScreen(void)
Эта функция нужна только если мы меняем widescreen разрешение? Для обычного мы можем не вызывать ее?

2024-06-18 18:53 UTC, ivan-ushakov approved these changes

2024-06-18 19:15 UTC, Solant commented on MechoSoma/RUNTIME/arcane_menu.cpp
> +	// mch_arcScrD->objList->search(AE_BONUS_PART)->InitCoords("bonus_part");
выдавало segfault, я еще не отследил за что она отвечает

2024-06-18 19:22 UTC, Solant commented on MechoSoma/RUNTIME/arcane_menu.cpp
> +void mchReInitArcaneScreen(void)
нужна всегда когда будет меняться соотношение сторон, т.е. при переходе с 4:3 на 16:9, но при изменении разрешения с одним и тем же соотношением сторон она ничего не поменяет

не вызвать наверное можно, но нужно будет отслеживать текущее и новое соотношение. а есть причина ее не вызывать?

2024-06-20 09:12 UTC, Fenex commented on MechoSoma/RUNTIME/arcane_menu.cpp
> +void mchReInitArcaneScreen(void)
> нужна всегда когда будет меняться соотношение сторон

Тогда надо поменять и\или комментарий с упоминанием `aspect ratio`.

2024-06-20 10:00 UTC, Solant commented on MechoSoma/RUNTIME/arcane_menu.cpp
> +void mchReInitArcaneScreen(void)
Название давал как похожим функциям `mchReInitGraph` и `d3dReInit`, поэтому название я бы оставил

Предлагаю поменять комментарий на такой:
```cpp
/**
 * Change menu and UI screen items position with appropriate aspect ratio offsets
 */
```

2024-10-25 13:47 UTC, Solant commented
Добрый день 😀

Хотел узнать есть ли какие-то планы смержить/выпустить эти изменения? Возможно вместе с изменениями отсюда https://github.com/KD-lab-Open-Source/Samogonki/pull/97

2024-10-25 19:41 UTC, ivan-ushakov commented
> Добрый день 😀
> 
> Хотел узнать есть ли какие-то планы смержить/выпустить эти изменения? Возможно вместе с изменениями отсюда #97

Привет! Если все ОК, можно будет выпустить. @DileSoft твое мнение?

2025-02-23 09:40 UTC, ivan-ushakov commented on MechoSoma/iScreen/SCRIPTS/ISCREEN.SCR
> +		max_state	11
А новые `state_str $ACS_1600_STR` не нужно добавлять тут?

2025-03-01 10:06 UTC, merged